Priodically chech change log
catenax-ng/product-bpdm-cdq-bridge pull request #11
Opened 2023-04-12 20:10 UTC by fabiodmota

Just to review

2023-05-03 10:21 UTC, nicoprow requested changes

2023-05-03 10:21 UTC, nicoprow commented on src/main/resources/db/migration/V0_0_1_0__create_tables.sql
> +
migration files are validated by flyway over checksum. So if you change the migration file after it has been applied to a database it will result in an error. In general, never change the migration files after they have been created

2023-05-03 10:21 UTC, nicoprow commented on src/main/kotlin/com/catenax/bpdm/bridge/cdq/config/ClientsConfig.kt
> +        havingValue = "false", matchIfMissing = true
gate property name should mirror pool property name. But one is camel case, the other separated by dashes

2023-05-03 10:21 UTC, nicoprow commented on src/main/kotlin/com/catenax/bpdm/bridge/cdq/entity/SyncRecord.kt
> +        CHANGELOG_IMPORT
I think the types should be more expressive so it is immediatley obvious to which import/export operation they belong. Something like "Gate Import" and "Pool Export" or similar.

2023-05-03 10:21 UTC, nicoprow commented on src/main/resources/application.yml
> +        url: http://localhost:8080
They can't be running on the same port at the same time. Best use 8081 as default for the Gate here as this is also the Gate's default port.

2023-05-08 14:29 UTC, fabiodmota commented on src/main/resources/db/migration/V0_0_1_0__create_tables.sql
> +
noted !

2023-05-12 15:44 UTC, nicoprow approved these changes

2023-05-12 15:44 UTC, merged