Add sync entity and get endpoint from pool
catenax-ng/product-bpdm-cdq-bridge pull request #7
Opened 2023-04-06 14:09 UTC by fabiodmota

Add sync entity and get endpoint from pool

2023-04-12 15:00 UTC, nicoprow requested changes
SyncType issue (see comment)

2023-04-12 15:00 UTC, nicoprow commented on src/main/kotlin/com/catenax/bpdm/bridge/cdq/entity/SyncRecord.kt
> +    var type: SyncType,
Better to create an own SyncType in here since the Pool will not have a SAAS sync type soon. Alternatively, you currently don't need a type since you only have one type of sync. So you could delete the type if you wanted to. Since there will be another Sync for the Gate coming up I'm also ok with leaving the type here and adding a Gate Sync value to it later on.
In any case, the bridge needs its own synctype

2023-04-12 17:29 UTC, fabiodmota commented on src/main/kotlin/com/catenax/bpdm/bridge/cdq/entity/SyncRecord.kt
> +    var type: SyncType,
Add a new sync enumeration to the entity so we can change it and add new sync types in the future like you said, just changed the name since i think its better when importing it will appear both syncs and to not confuse have different names,

2023-04-13 12:16 UTC, nicoprow requested changes

2023-04-13 12:16 UTC, nicoprow commented on src/main/kotlin/com/catenax/bpdm/bridge/cdq/entity/SyncRecord.kt
> +        OPENSEARCH,
Remove OPENSEARCH here as it is not needed. The Bridge does not have an Opensearch Sync

2023-04-13 13:03 UTC, fabiodmota commented on src/main/kotlin/com/catenax/bpdm/bridge/cdq/entity/SyncRecord.kt
> +        OPENSEARCH,
Removed

2023-04-17 12:08 UTC, nicoprow approved these changes

2023-04-17 12:38 UTC, merged